### ISSUE TITLE
SVP AttrributeError

### ISSUE THREAD

**Issue by silvia2019** [sunspec/svp#3]
Getting AttributeError when adding a new test:

    Traceback (most recent call last):
      File "ui.py", line 1426, in OnTreeCtrlLeftDown
        item, flags = self.tree.HitTest(event.GetPosition())
      File "/home/silvia/sunspec/svp/svptreectrl.py", line 7632, in HitTest
        hit, flags = self._anchor.HitTest(point, self, flags, 0)
      File "/home/silvia/sunspec/svp/svptreectrl.py", line 2588, in HitTest
        res, flags = child.HitTest(point, theCtrl, flags, level + 1)
      File "/home/silvia/sunspec/svp/svptreectrl.py", line 2519, in HitTest
        if point.y > self._y and point.y < self._y + h:
    AttributeError: 'tuple' object has no attribute 'y'

The open svp svptreectrl.py module has the syntax:

    def HitTest(self, point, theCtrl, flags=0, level=0):
        ...
        point = self.CalcUnscrolledPosition(*point)

The returning point does hot have the x, y attributes.  The issue is seen in Ubuntu 18.04 and Windows 10.

**Comment by EugeneRNCan** [comment]
Hi, i had this issue this morning. The solution is to change all the point.y by point[1] and all the point.x by point[0] and it worked for me after that.

**Comment by silvia2019** [comment]
Thank you.  The code is being updated and will be going through testing for this issue.

**Comment by silvia2019** [comment]
Changing the line to:
    `point = wx.Point(self.CalcUnscrolledPosition(*point))` 

resolves this issue.

**Comment by silvia2019** [comment]
Resolved with pull request.
